/**
 * Country data for GeoLocation selection
 * Format: { id: number, name: string }
 */

const CountriesData = {
    countries: [
        { id: 244, name: "United States" },
        { id: 242, name: "United Kingdom" },
        { id: 39, name: "Canada" },
        { id: 12, name: "Australia" },
        { id: 94, name: "Germany" },
        { id: 84, name: "France" },
        { id: 217, name: "Spain" },
        { id: 118, name: "Italy" },
        { id: 176, name: "Netherlands" },
        { id: 21, name: "Belgium" },
        { id: 223, name: "Switzerland" },
        { id: 14, name: "Austria" },
        { id: 191, name: "Poland" },
        { id: 75, name: "Czech Republic" },
        { id: 221, name: "Sweden" },
        { id: 177, name: "Norway" },
        { id: 77, name: "Denmark" },
        { id: 83, name: "Finland" },
        { id: 113, name: "India" },
        { id: 45, name: "China" },
        { id: 122, name: "Japan" },
        { id: 134, name: "South Korea" },
        { id: 203, name: "Russia" },
        { id: 32, name: "Brazil" },
        { id: 158, name: "Mexico" },
        { id: 7, name: "Argentina" },
        { id: 46, name: "Chile" },
        { id: 51, name: "Colombia" },
        { id: 18, name: "Belarus" },
        { id: 22, name: "Belize" },
        { id: 23, name: "Benin" },
        { id: 25, name: "Bhutan" },
        { id: 26, name: "Bolivia" },
        { id: 27, name: "Bosnia and Herzegovina" },
        { id: 29, name: "Botswana" },
        { id: 33, name: "Brunei" },
        { id: 34, name: "Bulgaria" },
        { id: 35, name: "Burkina Faso" },
        { id: 36, name: "Burundi" },
        { id: 37, name: "Cambodia" },
        { id: 38, name: "Cameroon" },
        { id: 40, name: "Cape Verde" },
        { id: 41, name: "Central African Republic" },
        { id: 42, name: "Chad" },
        { id: 47, name: "Comoros" },
        { id: 48, name: "Congo" },
        { id: 49, name: "Congo (DRC)" },
        { id: 50, name: "Cook Islands" },
        { id: 52, name: "Costa Rica" },
        { id: 53, name: "Côte d'Ivoire" },
        { id: 54, name: "Croatia" },
        { id: 55, name: "Cuba" },
        { id: 57, name: "Cyprus" },
        { id: 59, name: "Djibouti" },
        { id: 60, name: "Dominica" },
        { id: 61, name: "Dominican Republic" },
        { id: 62, name: "Ecuador" },
        { id: 63, name: "Egypt" },
        { id: 64, name: "El Salvador" },
        { id: 65, name: "Equatorial Guinea" },
        { id: 66, name: "Eritrea" },
        { id: 67, name: "Estonia" },
        { id: 68, name: "Ethiopia" },
        { id: 69, name: "Falkland Islands" },
        { id: 70, name: "Faroe Islands" },
        { id: 71, name: "Fiji" },
        { id: 72, name: "French Polynesia" },
        { id: 73, name: "Gabon" },
        { id: 74, name: "Gambia" },
        { id: 76, name: "Georgia" },
        { id: 78, name: "Gibraltar" },
        { id: 79, name: "Greece" },
        { id: 80, name: "Greenland" },
        { id: 81, name: "Grenada" },
        { id: 82, name: "Guam" },
        { id: 85, name: "Guatemala" },
        { id: 86, name: "Guernsey" },
        { id: 87, name: "Guinea" },
        { id: 88, name: "Guinea-Bissau" },
        { id: 89, name: "Guyana" },
        { id: 90, name: "Haiti" },
        { id: 91, name: "Honduras" },
        { id: 92, name: "Hong Kong SAR" },
        { id: 93, name: "Hungary" },
        { id: 95, name: "Iceland" },
        { id: 96, name: "Indonesia" },
        { id: 97, name: "Iran" },
        { id: 98, name: "Iraq" },
        { id: 99, name: "Ireland" },
        { id: 100, name: "Isle of Man" },
        { id: 101, name: "Israel" },
        { id: 103, name: "Jamaica" },
        { id: 104, name: "Jan Mayen" },
        { id: 105, name: "Jersey" },
        { id: 106, name: "Jordan" },
        { id: 107, name: "Kazakhstan" },
        { id: 108, name: "Kenya" },
        { id: 109, name: "Kiribati" },
        { id: 110, name: "Kosovo" },
        { id: 111, name: "Kuwait" },
        { id: 112, name: "Kyrgyzstan" },
        { id: 114, name: "Laos" },
        { id: 115, name: "Latvia" },
        { id: 116, name: "Lebanon" },
        { id: 117, name: "Lesotho" },
        { id: 119, name: "Liberia" },
        { id: 120, name: "Libya" },
        { id: 121, name: "Liechtenstein" },
        { id: 123, name: "Lithuania" },
        { id: 124, name: "Luxembourg" },
        { id: 125, name: "Macao SAR" },
        { id: 126, name: "North Macedonia" },
        { id: 127, name: "Madagascar" },
        { id: 128, name: "Malawi" },
        { id: 129, name: "Malaysia" },
        { id: 130, name: "Maldives" },
        { id: 131, name: "Mali" },
        { id: 132, name: "Malta" },
        { id: 133, name: "Marshall Islands" },
        { id: 135, name: "Mauritania" },
        { id: 136, name: "Mauritius" },
        { id: 137, name: "Mayotte" },
        { id: 139, name: "Micronesia" },
        { id: 140, name: "Moldova" },
        { id: 141, name: "Monaco" },
        { id: 142, name: "Mongolia" },
        { id: 143, name: "Montenegro" },
        { id: 144, name: "Montserrat" },
        { id: 145, name: "Morocco" },
        { id: 146, name: "Mozambique" },
        { id: 147, name: "Myanmar" },
        { id: 148, name: "Namibia" },
        { id: 149, name: "Nauru" },
        { id: 150, name: "Nepal" },
        { id: 152, name: "New Caledonia" },
        { id: 153, name: "New Zealand" },
        { id: 154, name: "Nicaragua" },
        { id: 155, name: "Niger" },
        { id: 156, name: "Nigeria" },
        { id: 157, name: "Niue" },
        { id: 159, name: "Norfolk Island" },
        { id: 160, name: "North Korea" },
        { id: 161, name: "Northern Mariana Islands" },
        { id: 163, name: "Oman" },
        { id: 164, name: "Pakistan" },
        { id: 165, name: "Palau" },
        { id: 166, name: "Palestinian Authority" },
        { id: 167, name: "Panama" },
        { id: 168, name: "Papua New Guinea" },
        { id: 169, name: "Paraguay" },
        { id: 170, name: "Peru" },
        { id: 171, name: "Philippines" },
        { id: 172, name: "Pitcairn Islands" },
        { id: 174, name: "Portugal" },
        { id: 175, name: "Puerto Rico" },
        { id: 178, name: "Qatar" },
        { id: 179, name: "Réunion" },
        { id: 180, name: "Romania" },
        { id: 181, name: "Rwanda" },
        { id: 182, name: "Saint Barthélemy" },
        { id: 183, name: "Saint Kitts and Nevis" },
        { id: 184, name: "Saint Lucia" },
        { id: 185, name: "Saint Martin" },
        { id: 186, name: "Saint Pierre and Miquelon" },
        { id: 187, name: "Saint Vincent and the Grenadines" },
        { id: 188, name: "Samoa" },
        { id: 189, name: "San Marino" },
        { id: 190, name: "São Tomé and Príncipe" },
        { id: 192, name: "Saudi Arabia" },
        { id: 193, name: "Senegal" },
        { id: 194, name: "Serbia" },
        { id: 195, name: "Seychelles" },
        { id: 196, name: "Sierra Leone" },
        { id: 197, name: "Singapore" },
        { id: 198, name: "Sint Maarten" },
        { id: 199, name: "Slovakia" },
        { id: 200, name: "Slovenia" },
        { id: 201, name: "Solomon Islands" },
        { id: 202, name: "Somalia" },
        { id: 204, name: "South Africa" },
        { id: 205, name: "South Georgia and the South Sandwich Islands" },
        { id: 206, name: "South Sudan" },
        { id: 207, name: "Sri Lanka" },
        { id: 208, name: "Sudan" },
        { id: 209, name: "Suriname" },
        { id: 210, name: "Svalbard" },
        { id: 211, name: "Swaziland" },
        { id: 213, name: "Syria" },
        { id: 214, name: "Taiwan" },
        { id: 215, name: "Tajikistan" },
        { id: 216, name: "Tanzania" },
        { id: 218, name: "Thailand" },
        { id: 219, name: "Timor-Leste" },
        { id: 220, name: "Togo" },
        { id: 222, name: "Tokelau" },
        { id: 224, name: "Tonga" },
        { id: 225, name: "Trinidad and Tobago" },
        { id: 226, name: "Tunisia" },
        { id: 227, name: "Turkey" },
        { id: 228, name: "Turkmenistan" },
        { id: 229, name: "Turks and Caicos Islands" },
        { id: 230, name: "Tuvalu" },
        { id: 231, name: "Uganda" },
        { id: 232, name: "Ukraine" },
        { id: 233, name: "United Arab Emirates" },
        { id: 234, name: "United States Minor Outlying Islands" },
        { id: 235, name: "Uruguay" },
        { id: 236, name: "Uzbekistan" },
        { id: 237, name: "Vanuatu" },
        { id: 238, name: "Vatican City" },
        { id: 239, name: "Venezuela" },
        { id: 240, name: "Vietnam" },
        { id: 241, name: "Virgin Islands" },
        { id: 243, name: "Wallis and Futuna" },
        { id: 245, name: "Yemen" },
        { id: 246, name: "Zambia" },
        { id: 247, name: "Zimbabwe" }
    ],

    /**
     * Get country by ID
     */
    getCountryById(id) {
        return this.countries.find(c => c.id === parseInt(id));
    },

    /**
     * Get country name by ID
     */
    getCountryName(id) {
        const country = this.getCountryById(id);
        return country ? country.name : 'Unknown';
    },

    /**
     * Populate a select element with all countries
     */
    populateSelect(selectElement, selectedId = 244) {
        selectElement.innerHTML = '';
        this.countries.forEach(country => {
            const option = document.createElement('option');
            option.value = country.id;
            option.textContent = country.name;
            if (country.id === parseInt(selectedId)) {
                option.selected = true;
            }
            selectElement.appendChild(option);
        });
    }
};
