/**
 * Language and keyboard layout data
 */

const LanguagesData = {
    languages: [
        { code: 'en-US', name: 'English (United States)' },
        { code: 'en-GB', name: 'English (United Kingdom)' },
        { code: 'de-DE', name: 'German (Germany)' },
        { code: 'fr-FR', name: 'French (France)' },
        { code: 'es-ES', name: 'Spanish (Spain)' },
        { code: 'it-IT', name: 'Italian (Italy)' },
        { code: 'ja-JP', name: 'Japanese (Japan)' },
        { code: 'zh-CN', name: 'Chinese (Simplified)' },
        { code: 'pt-BR', name: 'Portuguese (Brazil)' },
        { code: 'ru-RU', name: 'Russian (Russia)' },
        { code: 'ko-KR', name: 'Korean (Korea)' },
        { code: 'nl-NL', name: 'Dutch (Netherlands)' },
        { code: 'pl-PL', name: 'Polish (Poland)' },
        { code: 'sv-SE', name: 'Swedish (Sweden)' },
        { code: 'tr-TR', name: 'Turkish (Turkey)' },
        { code: 'ar-SA', name: 'Arabic (Saudi Arabia)' },
        { code: 'cs-CZ', name: 'Czech (Czech Republic)' },
        { code: 'da-DK', name: 'Danish (Denmark)' },
        { code: 'fi-FI', name: 'Finnish (Finland)' },
        { code: 'el-GR', name: 'Greek (Greece)' },
        { code: 'he-IL', name: 'Hebrew (Israel)' },
        { code: 'hu-HU', name: 'Hungarian (Hungary)' },
        { code: 'no-NO', name: 'Norwegian (Norway)' },
        { code: 'pt-PT', name: 'Portuguese (Portugal)' },
        { code: 'ro-RO', name: 'Romanian (Romania)' },
        { code: 'sk-SK', name: 'Slovak (Slovakia)' },
        { code: 'th-TH', name: 'Thai (Thailand)' },
        { code: 'uk-UA', name: 'Ukrainian (Ukraine)' },
        { code: 'vi-VN', name: 'Vietnamese (Vietnam)' },
        { code: 'zh-TW', name: 'Chinese (Traditional)' }
    ],

    keyboards: [
        { code: '0409:00000409', name: 'US' },
        { code: '0809:00000809', name: 'UK' },
        { code: '0407:00000407', name: 'German' },
        { code: '040c:0000040c', name: 'French' },
        { code: '0c0a:0000040a', name: 'Spanish' },
        { code: '0410:00000410', name: 'Italian' },
        { code: '0411:00000411', name: 'Japanese' },
        { code: '0804:00000804', name: 'Chinese (Simplified)' },
        { code: '0416:00000416', name: 'Portuguese (Brazil)' },
        { code: '0419:00000419', name: 'Russian' },
        { code: '0412:00000412', name: 'Korean' },
        { code: '0413:00000413', name: 'Dutch' },
        { code: '0415:00000415', name: 'Polish' },
        { code: '041d:0000041d', name: 'Swedish' },
        { code: '041f:0000041f', name: 'Turkish' },
        { code: '0401:00000401', name: 'Arabic' },
        { code: '0405:00000405', name: 'Czech' },
        { code: '0406:00000406', name: 'Danish' },
        { code: '040b:0000040b', name: 'Finnish' },
        { code: '0408:00000408', name: 'Greek' },
        { code: '040d:0000040d', name: 'Hebrew' },
        { code: '040e:0000040e', name: 'Hungarian' },
        { code: '0414:00000414', name: 'Norwegian' },
        { code: '0816:00000816', name: 'Portuguese' },
        { code: '0418:00000418', name: 'Romanian' },
        { code: '041b:0000041b', name: 'Slovak' },
        { code: '041e:0000041e', name: 'Thai' },
        { code: '0422:00000422', name: 'Ukrainian' },
        { code: '042a:0000042a', name: 'Vietnamese' },
        { code: '0404:00000404', name: 'Chinese (Traditional)' }
    ],

    timezones: [
        { id: 'Dateline Standard Time', name: '(UTC-12:00) International Date Line West' },
        { id: 'UTC-11', name: '(UTC-11:00) Coordinated Universal Time-11' },
        { id: 'Hawaiian Standard Time', name: '(UTC-10:00) Hawaii' },
        { id: 'Alaskan Standard Time', name: '(UTC-09:00) Alaska' },
        { id: 'Pacific Standard Time', name: '(UTC-08:00) Pacific Time (US & Canada)' },
        { id: 'Mountain Standard Time', name: '(UTC-07:00) Mountain Time (US & Canada)' },
        { id: 'Central Standard Time', name: '(UTC-06:00) Central Time (US & Canada)' },
        { id: 'Eastern Standard Time', name: '(UTC-05:00) Eastern Time (US & Canada)' },
        { id: 'Atlantic Standard Time', name: '(UTC-04:00) Atlantic Time (Canada)' },
        { id: 'Newfoundland Standard Time', name: '(UTC-03:30) Newfoundland' },
        { id: 'E. South America Standard Time', name: '(UTC-03:00) Brasilia' },
        { id: 'UTC', name: '(UTC) Coordinated Universal Time' },
        { id: 'GMT Standard Time', name: '(UTC+00:00) Dublin, Edinburgh, Lisbon, London' },
        { id: 'W. Europe Standard Time', name: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna' },
        { id: 'Central Europe Standard Time', name: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague' },
        { id: 'Romance Standard Time', name: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris' },
        { id: 'Central European Standard Time', name: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb' },
        { id: 'FLE Standard Time', name: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius' },
        { id: 'GTB Standard Time', name: '(UTC+02:00) Athens, Bucharest' },
        { id: 'Israel Standard Time', name: '(UTC+02:00) Jerusalem' },
        { id: 'E. Europe Standard Time', name: '(UTC+02:00) Chisinau' },
        { id: 'Egypt Standard Time', name: '(UTC+02:00) Cairo' },
        { id: 'Russian Standard Time', name: '(UTC+03:00) Moscow, St. Petersburg, Volgograd' },
        { id: 'Arab Standard Time', name: '(UTC+03:00) Kuwait, Riyadh' },
        { id: 'Arabian Standard Time', name: '(UTC+04:00) Abu Dhabi, Muscat' },
        { id: 'Iran Standard Time', name: '(UTC+03:30) Tehran' },
        { id: 'Afghanistan Standard Time', name: '(UTC+04:30) Kabul' },
        { id: 'Pakistan Standard Time', name: '(UTC+05:00) Islamabad, Karachi' },
        { id: 'India Standard Time', name: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi' },
        { id: 'Nepal Standard Time', name: '(UTC+05:45) Kathmandu' },
        { id: 'Central Asia Standard Time', name: '(UTC+06:00) Astana' },
        { id: 'Myanmar Standard Time', name: '(UTC+06:30) Yangon (Rangoon)' },
        { id: 'SE Asia Standard Time', name: '(UTC+07:00) Bangkok, Hanoi, Jakarta' },
        { id: 'China Standard Time', name: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi' },
        { id: 'Singapore Standard Time', name: '(UTC+08:00) Kuala Lumpur, Singapore' },
        { id: 'Taipei Standard Time', name: '(UTC+08:00) Taipei' },
        { id: 'W. Australia Standard Time', name: '(UTC+08:00) Perth' },
        { id: 'Tokyo Standard Time', name: '(UTC+09:00) Osaka, Sapporo, Tokyo' },
        { id: 'Korea Standard Time', name: '(UTC+09:00) Seoul' },
        { id: 'AUS Central Standard Time', name: '(UTC+09:30) Adelaide' },
        { id: 'Cen. Australia Standard Time', name: '(UTC+09:30) Darwin' },
        { id: 'AUS Eastern Standard Time', name: '(UTC+10:00) Canberra, Melbourne, Sydney' },
        { id: 'E. Australia Standard Time', name: '(UTC+10:00) Brisbane' },
        { id: 'Tasmania Standard Time', name: '(UTC+10:00) Hobart' },
        { id: 'Central Pacific Standard Time', name: '(UTC+11:00) Solomon Is., New Caledonia' },
        { id: 'New Zealand Standard Time', name: '(UTC+12:00) Auckland, Wellington' },
        { id: 'Fiji Standard Time', name: '(UTC+12:00) Fiji' },
        { id: 'Tonga Standard Time', name: '(UTC+13:00) Nuku\'alofa' }
    ]
};
